### ISSUE TITLE
error by pub.exe

### ISSUE THREAD

**Issue by isharrrry** [jinyuttt/ObserverDDS#2]
System.IO.FileNotFoundException:“未能加载文件或程序集“System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。”

**Comment by jinyuttt** [comment]
已经修改，需要引用其它版本程序，微软在修改库，微软更新比较快
